- name: Mongodb setup playbook
  hosts: mongodb
  become: yes

  tasks:
    - name: Setup mongodb repo
      copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    
    - name: Install mongodb
      yum:
        name: mongodb-org
        state: present
    
    - name: Start & Enable MongoDB Service
      service:
        name: mongod
        state: started
        enabled: yes
    
    - name: Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
      replace:
        path: /etc/mongod.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
    
    - name: Restart the service
      service:
        name: mongod
        state: restarted