- name: Playbook for installing mysql
  hosts: mysql
  become: yes

  tasks:
    - name: Disable mysql 8 version
      shell: yum module disable mysql -y 

    - name: Setup mysql repo
      copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo
    
    - name: Install MySQL Server
      yum:
        name: mysql-community-server
        state: present
    
    - name: Start and Enable MySQL Service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Setup password for mysql
      shell: mysql_secure_installation --set-root-pass RoboShop@1
