- name: Playbook for rabbitmq
  hosts: rabbitmq
  become: yes

  tasks:
    - name: Configure YUM Repos from the script provided by vendor
      command: "{{ item }}"
      with_items:
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"

    - name: Install RabbitMQ
      yum:
        name: rabbitmq-server
        state: present

    - name: Start and Enable RabbitMQ service
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
    
    - name: Set password and permissions for rabbitmq
      command: "{{ item }}"
      with_items:
        - rabbitmqctl add_user roboshop roboshop123
        - rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"