- name: Playbook for web service
  hosts: web
  become: yes

  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    
    - name: Start & Enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
    
    - name: Remove the default content that web server is serving
      shell: rm -rf /usr/share/nginx/html/*

    - name: Download the frontend content and extract
      unarchive:
        src: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    
    - name: Create Nginx Reverse Proxy Configuration
      copy:
        src: roboshop.conf
        dest: /nginx/default.d/roboshop.conf
    
    - name: Restart Nginx Service to load the changes of the configuration
      service:
        name: nginx
        state: restarted


